### ISSUE TITLE
It appears this code attempts to attack a significantly weaker cipher than what is claimed.

### ISSUE THREAD

**Issue by michaelkounavis** [mahzoun/K-Cipher#1]
I glanced at the code. The code does not seem to attack K-Cipher. Specifically  the attacks are on a much weaker version where randomisers are deterministic functions of the key, which in the code is also constant:

for (int i = 0; i < 6; i++) {
        t[0] = key_val[2 * i + 2];
        t[1] = key_val[2 * i + 3];
        for (int j = 0; j < 128; j++)
            randomizers[i][j] = j < 64 ? t[0][j] : t[1][j - 64];
    }

K-Cipher intentionally sets the randomizers to be random, uniformly distributed, and secret. They are not known to the attacker. In addition, the randomisers are drawn independently from the key. But this is not what the attacked cipher does.

**Comment by mahzoun** [comment]
Thank you for your comment. As you can see in the `main.cpp` file, on line 19 there is a random constant of size `14 * 64`. I copied this data from the [k-cipher paper ](https://eprint.iacr.org/2020/030.pdf) (last page). The reason that I used this data was to test the implementation that works correctly. I assumed they are independent and random as they are suggested by the designers. These `14 * 64` bits are typecasted to bitset in the init function for easier implementation. So the randomizers and the master key are indeed independent and hidden from the attacker. In the current version of the attack, one can simply remove the constant and generate random values for keys in each run of the code. 
But I will update the Init function to be more clear. Let me know if it's still unclear.

**Comment by michaelkounavis** [comment]
I see, thank you. Yes this version now is clearer. I will study the attack and come back to you and your team with comments.
